# Generated by Django 2.1.7 on 2021-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
