# Generated by Django 2.1.7 on 2021-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211026_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default='/user/logo.png', max_length=200),
        ),
    ]
